name: ros_package_build

on:

  push:
    branches: [ 1.5 ]

  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    uses: ctu-mrs/ci_scripts/.github/workflows/ros_package_build.yml@master
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
